### ISSUE TITLE
my-mummer-2-vcf.py:  TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by owenwilkins** [MatteoSchiavinato/Utilities#2]
Hello @MatteoSchiavinato , 

I am experiencing the above error when trying to run `my-mummer-2-vcf.py`, and was hoping you might be able to help me resolve it. I am running the script using: 

`python3 my-mummer-2-vcf.py --input-header -s nucmer.snps` and have tried this with and without `--input-header`. 

I am running *nucmer* and *show-snps* using: 
```nucmer -c 100 -p xxx output.backbone.fasta xxx.fasta```
```show-snps -CTlr xxx.delta > nucmer.snps```

I have tried using `show-snps -T xxx.delta > nucmer.snps``` also, and receive the same error. 

The output from `head nucmer.snps | awk '{print NF}'` is: 
`2
1
0
12
12
12
12
12
12
12`

and the output from `head nucmer.snps | awk '{print NF; print $0}'` is: 

2
/dartfs-hpc/rc/lab/G/output.backbone.fasta /dartfs-hpc/rc/lab/G/output.GCF_000480355.1_Pseu_aeru_CF614_V1.accessory.fasta
1
NUCMER
0

12
[P1]	[SUB]	[SUB]	[P2]	[BUFF]	[DIST]	[LEN R]	[LEN Q]	[FRM]	[TAGS]
12
792	G	C	35454	1	792	2482	37520	1	1	backbone_0703_length_2482	GCF_000480355.1_Pseu_aeru_CF614_V1_accessory_1907_length_37520
12
793	G	A	35455	1	793	2482	37520	1	1	backbone_0703_length_2482	GCF_000480355.1_Pseu_aeru_CF614_V1_accessory_1907_length_37520
12
795	G	C	35457	2	795	2482	37520	1	1	backbone_0703_length_2482	GCF_000480355.1_Pseu_aeru_CF614_V1_accessory_1907_length_37520
12
801	T	C	35463	4	801	2482	37520	1	1	backbone_0703_length_2482	GCF_000480355.1_Pseu_aeru_CF614_V1_accessory_1907_length_37520
12
805	.	A	35468	4	805	2482	37520	1	1	backbone_0703_length_2482	GCF_000480355.1_Pseu_aeru_CF614_V1_accessory_1907_length_37520
12
809	A	.	35471	1	809	2482	37520	1	1	backbone_0703_length_2482	GCF_000480355.1_Pseu_aeru_CF614_V1_accessory_1907_length_37520

Any thoughts you have on why this may be occurring and how I might go about solving it would be much appreciated. 

Thanks in advance!! 

**The error in full is:**

```
  File "/dartfs-hpc/rc/home/d/d41294d/.conda/envs/biopyow/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 42, in __init__
    self.stream = open(source, "r" + mode)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "my-mummer-2-vcf.py", line 329, in <module>
    Vcf_lines = collapse_variants(args.reference, Vcf_lines)
  File "my-mummer-2-vcf.py", line 211, in collapse_variants
    Sequences = parse_sequences(Reference)
  File "my-mummer-2-vcf.py", line 189, in parse_sequences
    for record in SeqIO.parse(Reference, "fasta"):
  File "/dartfs-hpc/rc/home/d/d41294d/.conda/envs/biopyow/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 627, in parse
    i = iterator_generator(handle)
  File "/dartfs-hpc/rc/home/d/d41294d/.conda/envs/biopyow/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 181, in __init__
    super().__init__(source, alphabet=alphabet, mode="t", fmt="Fasta")
  File "/dartfs-hpc/rc/home/d/d41294d/.conda/envs/biopyow/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 46, in __init__
    if source.read(0) != "":
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by MatteoSchiavinato** [comment]
Hi! Sorry for the delayed reply. Project deadlines are kicking in. 

Firstly, your input file has a header so you definitely have to use `--input-header` (since you said you tried with and without). 

Secondly, it seems that the error might be raised by the fact that there is something that looks like a path, or that doesn't have a type, where there should be a string.

Did you check your input files, are they perfect? Just because it looks like the type of error you'd get when the input file is corrupted.

Also, could you please provide the version of nucmer / mummer that you used? As far as I could tell, there were some portability issues between 3.* and 4.*.

**Comment by owenwilkins** [comment]
No problem, thanks for getting back! 

Input files look good, although if you have any other thoughts on how to check them im happy to try it. 

I tried both mummer 3 and 4 and unfortuantely got the same result. 

I'm not sure it it would also be helpful, but seems that it came up in the other issue. I am running on an HPC with a conda installation of mummer/nucmer. I tried running locally with a local conda installation of mummer, and got the same issue. 

Thanks again,

**Comment by MatteoSchiavinato** [comment]
Could you send me a subset of your snps file?  I can try to run it on our cluster and see if I get the same error. It would also help me debugging it.

**Comment by owenwilkins** [comment]
Sure thing. 

[nucmer.sub.snps.zip](https://github.com/MatteoSchiavinato/Utilities/files/5023078/nucmer.sub.snps.zip)

**Comment by MatteoSchiavinato** [comment]
I think I found the issue. For some reason, I left the `--reference` option not mandatory, but one of the functions wanted it.  And you're the first person who's not declaring the `--reference`, so the first to bring up the issue. 

I made a new commit to the program, could you try to download it again, and re-try?

**Comment by MatteoSchiavinato** [comment]
I will close the issue for now, since it seems it solved your problem.
