### ISSUE TITLE
suppress mummer2vcf to output a wrong 'alt' when SNPs at the same position in two (or more) reference sequences

### ISSUE THREAD

**Issue by mickeykawai** [MatteoSchiavinato/Utilities#3]
Hi Matteo, 

It's nice you put this my-mummer-2-vcf.py available for us. 
I think following fixes are necessary for some cases. 

1. When SNPs exist at the same position in two (or more) reference sequences and 'alt' bases differ each other, this code outputs a wrong 'alt' of concatenated bases. 

An example fix is itemgetter(0, 1) instead of itemgetter(1) at line 223 in def collapse_variants. 

`	Sorted_snps = [ "\t".join([str(y) for y in x]) for x in sorted(Sorted_snps, key=itemgetter(0,1)) ]`

2. When SNPs exist at the same position in two (or more) query sequences (whether 'alt' bases differ each other or not), this code does not output concatenated 'orig_pos'. 

If we want to output this, an example would be addition of following lines after line 114 of def collapse_snps. 

```
			orig_pos_lst = str(Collapsed_snps[-1][8]).split(",")
			orig_pos_lst.append(str(orig_pos))
			Collapsed_snps[-1][8] = ",".join(orig_pos_lst)
```

**Comment by MatteoSchiavinato** [comment]
Hi,
Thanks for the comments and suggestions. In order for me to take care of it, could you maybe provide:

- The command you used
- a subset of the files that generated the issue

So that I can test it out and fix it? :)

**Comment by mickeykawai** [comment]
my-mummer-2-vcf.py --input-header -t SNP -s _example.snps -g \<fastapath\>

Attached is the same as _example.snps, except I modified reference sequence names and removed header lines. 
[_example_manu.snps.zip](https://github.com/MatteoSchiavinato/Utilities/files/5236980/_example_manu.snps.zip)

For the first point, an example is two lines of position 20678 in seq_A and seq_B. 
For the second point, an example is two lines of position 20675 in seq_B for contig_1_length_880190_depth_1.05x and contig_5_length_220119_depth_0.89x.

**Comment by mickeykawai** [comment]
Even when with -t SNP, the script claims the correct fastafile path should be given for -g, so above example alone isn't enough to run the script for test...

**Comment by mickeykawai** [comment]
Following with the attached example is an example to reproduce with Mummer 3.23. 
```
nucmer -c 65 -l 65 --maxmatch -p ref_query ref.fa query.fa 
show-snps -T ref_query.delta > ref_query.snps
tail -n+5 ref_query.snps > ref_query.wo_header.snps

my-mummer-2-vcf.py -s ref_query.wo_header.snps -g ref.fa
```
will output as follows. 
```
a	100	.	A	G	.	.	.	y:100
a	101	.	A	G	.	.	.	y:101
a	102	.	G	C,T	.	.	.	x:102
```
After addition of above my modifications, output will be as follows. 
```
a	100	.	A	G	.	.	.	y:100
a	101	.	A	G	.	.	.	y:101
a	102	.	G	C,T	.	.	.	x:102,y:102
b	100	.	A	G	.	.	.	y:100
b	101	.	A	G	.	.	.	y:101
b	102	.	T	C	.	.	.	x:102
```
[_example_manu2.zip](https://github.com/MatteoSchiavinato/Utilities/files/5237289/_example_manu2.zip)

**Comment by MatteoSchiavinato** [comment]
So, I'm trying your modifications and they seem to work fine. Thanks for the suggestions! They fixed a quite relevant issue.
One thing: 
In your original post you mention "line 223" but I have that line at 220. I suppose your 223 is after you added also the other three lines (those you suggest to add after line 114). 
Is this a fair assumption? Or did I get it wrong?

**Comment by MatteoSchiavinato** [comment]
If you can, could you git clone it anew, and use it again? I have added your fixies to the latest push.

**Comment by mickeykawai** [comment]
Thank you, the script now works fine. Yes, line 220 instead of 223. The updated script is the same as what I myself modified as above. Thanks for your quick update!

**Comment by MatteoSchiavinato** [comment]
Thank _you_ for having found this issue, and proving once more why github is an amazing place for developers!

**Comment by mpallocc** [comment]
Caro Matteo,

sorry to reopen the issue but we noticed a similar behaviour concerning INDELS, i.e. for insertion the bases are concatenated and all the source sequences are collapsed into one.

attaching input and output. -t SNP works fine, -t INDELS shows the weird behaviour on insertion starting on base 5.

The issue I think lies in the "collapse_indel" function. Still didn't think of a solution, though. 

[snps.zip](https://github.com/MatteoSchiavinato/Utilities/files/5346606/snps.zip)

**Comment by MatteoSchiavinato** [comment]
Hi, 
Thanks for letting me know. I will have a look and get back at you!

**Comment by MatteoSchiavinato** [comment]
I'm working on it now. What reference did you use? I would need it to replicate the issue.

**Comment by mpallocc** [comment]
Here's attached the reference! 
[ref_covid-reference.fasta.zip](https://github.com/MatteoSchiavinato/Utilities/files/5371950/ref_covid-reference.fasta.zip)

**Comment by MatteoSchiavinato** [comment]
The version that I just uploaded produced the right output in my tests. For now I'm closing the issue since it seems to be solved, at least for me! I hope it serves your purpose. I wasn't handling properly the indels coming from two different sequences at the same position. Thanks for bringing it up! And good luck with our friend corona in these days of intense research.

**Comment by mpallocc** [comment]
Thank you so much! We'll have extensive testing in the next days and let you know.
